using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Numerics;

namespace Provadia_Numbers
{
    class Program
    {
        static void Main(string[] args)
        {
            BigInteger n = BigInteger.Parse(Console.ReadLine());
            ConvertToBase(n, 256);
        }


        private static void ConvertToBase(BigInteger number, int baseSystem)
        {
            BigInteger n = number;
            List<string> num = new List<string>();
            string c;
            do
            {
                c = IntToLetter((int)(n % baseSystem));
                num.Add(c);
                n /= baseSystem;
            }
            while (n > 0);

            //StringBuilder returnN = new StringBuilder();
            for (int i = num.Count-1; i >= 0; i--)
            {
                Console.Write(num[i]);
            }
            //return num.ToString();
        }

        private static string IntToLetter(int n)
        {
            switch (n)
            {
                case 0:
                    return "A";
                case 1:
                    return "B";
                case 2:
                    return "C";
                case 3:
                    return "D";
                case 4:
                    return "E";
                case 5:
                    return "F";
                case 6:
                    return "G";
                case 7:
                    return "H";
                case 8:
                    return "I";
                case 9:
                    return "J";
                case 10:
                    return "K";
                case 11:
                    return "L";
                case 12:
                    return "M";
                case 13:
                    return "N";
                case 14:
                    return "O";
                case 15:
                    return "P";
                case 16:
                    return "Q";
                case 17:
                    return "R";
                case 18:
                    return "S";
                case 19:
                    return "T";
                case 20:
                    return "U";
                case 21:
                    return "V";
                case 22:
                    return "W";
                case 23:
                    return "X";
                case 24:
                    return "Y";
                case 25:
                    return "Z";
                case 26:
                    return "aA";
                case 27:
                    return "aB";
                case 28:
                    return "aC";
                case 29:
                    return "aD";
                case 30:
                    return "aE";
                case 31:
                    return "aF";
                case 32:
                    return "aG";
                case 33:
                    return "aH";
                case 34:
                    return "aI";
                case 35:
                    return "aJ";
                case 36:
                    return "aK";
                case 37:
                    return "aL";
                case 38:
                    return "aM";
                case 39:
                    return "aN";
                case 40:
                    return "aO";
                case 41:
                    return "aP";
                case 42:
                    return "aQ";
                case 43:
                    return "aR";
                case 44:
                    return "aS";
                case 45:
                    return "aT";
                case 46:
                    return "aU";
                case 47:
                    return "aV";
                case 48:
                    return "aW";
                case 49:
                    return "aX";
                case 50:
                    return "aY";
                case 51:
                    return "aZ";
                case 52:
                    return "bA";
                case 53:
                    return "bB";
                case 54:
                    return "bC";
                case 55:
                    return "bD";
                case 56:
                    return "bE";
                case 57:
                    return "bF";
                case 58:
                    return "bG";
                case 59:
                    return "bH";
                case 60:
                    return "bI";
                case 61:
                    return "bJ";
                case 62:
                    return "bK";
                case 63:
                    return "bL";
                case 64:
                    return "bM";
                case 65:
                    return "bN";
                case 66:
                    return "bO";
                case 67:
                    return "bP";
                case 68:
                    return "bQ";
                case 69:
                    return "bR";
                case 70:
                    return "bS";
                case 71:
                    return "bT";
                case 72:
                    return "bU";
                case 73:
                    return "bV";
                case 74:
                    return "bW";
                case 75:
                    return "bX";
                case 76:
                    return "bY";
                case 77:
                    return "bZ";
                case 78:
                    return "cA";
                case 79:
                    return "cB";
                case 80:
                    return "cC";
                case 81:
                    return "cD";
                case 82:
                    return "cE";
                case 83:
                    return "cF";
                case 84:
                    return "cG";
                case 85:
                    return "cH";
                case 86:
                    return "cI";
                case 87:
                    return "cJ";
                case 88:
                    return "cK";
                case 89:
                    return "cL";
                case 90:
                    return "cM";
                case 91:
                    return "cN";
                case 92:
                    return "cO";
                case 93:
                    return "cP";
                case 94:
                    return "cQ";
                case 95:
                    return "cR";
                case 96:
                    return "cS";
                case 97:
                    return "cT";
                case 98:
                    return "cU";
                case 99:
                    return "cV";
                case 100:
                    return "cW";
                case 101:
                    return "cX";
                case 102:
                    return "cY";
                case 103:
                    return "cZ";
                case 104:
                    return "dA";
                case 105:
                    return "dB";
                case 106:
                    return "dC";
                case 107:
                    return "dD";
                case 108:
                    return "dE";
                case 109:
                    return "dF";
                case 110:
                    return "dG";
                case 111:
                    return "dH";
                case 112:
                    return "dI";
                case 113:
                    return "dJ";
                case 114:
                    return "dK";
                case 115:
                    return "dL";
                case 116:
                    return "dM";
                case 117:
                    return "dN";
                case 118:
                    return "dO";
                case 119:
                    return "dP";
                case 120:
                    return "dQ";
                case 121:
                    return "dR";
                case 122:
                    return "dS";
                case 123:
                    return "dT";
                case 124:
                    return "dU";
                case 125:
                    return "dV";
                case 126:
                    return "dW";
                case 127:
                    return "dX";
                case 128:
                    return "dY";
                case 129:
                    return "dZ";
                case 130:
                    return "eA";
                case 131:
                    return "eB";
                case 132:
                    return "eC";
                case 133:
                    return "eD";
                case 134:
                    return "eE";
                case 135:
                    return "eF";
                case 136:
                    return "eG";
                case 137:
                    return "eH";
                case 138:
                    return "eI";
                case 139:
                    return "eJ";
                case 140:
                    return "eK";
                case 141:
                    return "eL";
                case 142:
                    return "eM";
                case 143:
                    return "eN";
                case 144:
                    return "eO";
                case 145:
                    return "eP";
                case 146:
                    return "eQ";
                case 147:
                    return "eR";
                case 148:
                    return "eS";
                case 149:
                    return "eT";
                case 150:
                    return "eU";
                case 151:
                    return "eV";
                case 152:
                    return "eW";
                case 153:
                    return "eX";
                case 154:
                    return "eY";
                case 155:
                    return "eZ";
                case 156:
                    return "fA";
                case 157:
                    return "fB";
                case 158:
                    return "fC";
                case 159:
                    return "fD";
                case 160:
                    return "fE";
                case 161:
                    return "fF";
                case 162:
                    return "fG";
                case 163:
                    return "fH";
                case 164:
                    return "fI";
                case 165:
                    return "fJ";
                case 166:
                    return "fK";
                case 167:
                    return "fL";
                case 168:
                    return "fM";
                case 169:
                    return "fN";
                case 170:
                    return "fO";
                case 171:
                    return "fP";
                case 172:
                    return "fQ";
                case 173:
                    return "fR";
                case 174:
                    return "fS";
                case 175:
                    return "fT";
                case 176:
                    return "fU";
                case 177:
                    return "fV";
                case 178:
                    return "fW";
                case 179:
                    return "fX";
                case 180:
                    return "fY";
                case 181:
                    return "fZ";
                case 182:
                    return "gA";
                case 183:
                    return "gB";
                case 184:
                    return "gC";
                case 185:
                    return "gD";
                case 186:
                    return "gE";
                case 187:
                    return "gF";
                case 188:
                    return "gG";
                case 189:
                    return "gH";
                case 190:
                    return "gI";
                case 191:
                    return "gJ";
                case 192:
                    return "gK";
                case 193:
                    return "gL";
                case 194:
                    return "gM";
                case 195:
                    return "gN";
                case 196:
                    return "gO";
                case 197:
                    return "gP";
                case 198:
                    return "gQ";
                case 199:
                    return "gR";
                case 200:
                    return "gS";
                case 201:
                    return "gT";
                case 202:
                    return "gU";
                case 203:
                    return "gV";
                case 204:
                    return "gW";
                case 205:
                    return "gX";
                case 206:
                    return "gY";
                case 207:
                    return "gZ";
                case 208:
                    return "hA";
                case 209:
                    return "hB";
                case 210:
                    return "hC";
                case 211:
                    return "hD";
                case 212:
                    return "hE";
                case 213:
                    return "hF";
                case 214:
                    return "hG";
                case 215:
                    return "hH";
                case 216:
                    return "hI";
                case 217:
                    return "hJ";
                case 218:
                    return "hK";
                case 219:
                    return "hL";
                case 220:
                    return "hM";
                case 221:
                    return "hN";
                case 222:
                    return "hO";
                case 223:
                    return "hP";
                case 224:
                    return "hQ";
                case 225:
                    return "hR";
                case 226:
                    return "hS";
                case 227:
                    return "hT";
                case 228:
                    return "hU";
                case 229:
                    return "hV";
                case 230:
                    return "hW";
                case 231:
                    return "hX";
                case 232:
                    return "hY";
                case 233:
                    return "hZ";
                case 234:
                    return "iA";
                case 235:
                    return "iB";
                case 236:
                    return "iC";
                case 237:
                    return "iD";
                case 238:
                    return "iE";
                case 239:
                    return "iF";
                case 240:
                    return "iG";
                case 241:
                    return "iH";
                case 242:
                    return "iI";
                case 243:
                    return "iJ";
                case 244:
                    return "iK";
                case 245:
                    return "iL";
                case 246:
                    return "iM";
                case 247:
                    return "iN";
                case 248:
                    return "iO";
                case 249:
                    return "iP";
                case 250:
                    return "iQ";
                case 251:
                    return "iR";
                case 252:
                    return "iS";
                case 253:
                    return "iT";
                case 254:
                    return "iU";
                case 255:
                    return "iV";
            }
            return null;
        }
    }
}
